### ISSUE TITLE
Help this package be found?

### ISSUE THREAD

**Issue by OmgImAlexis** [sindresorhus/move-file-cli#3]
When searching for this I tried looking for "move cli" only for "trash-cli" to show up at the top and [this other](https://www.npmjs.com/package/move-cli) package show up on page two. This package isn't found on any page of the results.

Not sure if there's anything that can be done about this since "move cli" is two words and I don't think the npm keywords allows spaces.

Feel free to close this.

**Comment by sindresorhus** [comment]
It shows up at result number 14 for me: https://www.npmjs.com/search?q=move%20cli

I would recommend using https://npms.io/search?q=move-cli instead. It generally has a better search algorithm.

I don't think there's much I can do to improve the search ranking as I already have all the relevant keyboards in package.json.

**Comment by OmgImAlexis** [comment]
It's the space that's causing this from what I can tell. Searching with the hyphen on npm shows similar results to what `npms.io` shows.
